# Generated by Django 2.2.7 on 2022-02-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='make_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='shorturl',
            old_name='maker',
            new_name='creater',
        ),
    ]
